# Generated by Django 4.1.6 on 2023-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
